// Bundles the certificate, engine and handler into worker/dist/worker.js: one ES module that can be
// pasted into the Cloudflare dashboard or deployed with `npx wrangler deploy`.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const at = (p) => fileURLToPath(new URL(p, import.meta.url));
const parts = ['../js/certificate.js', '../js/engine.js', './handler.js'].map((p) => `// ---- ${p.replace(/^\.\.?\//, '')}\n` + readFileSync(at(p), 'utf8'));
mkdirSync(at('./dist'), { recursive: true });
writeFileSync(at('./dist/worker.js'), '// Generated by worker/build.mjs; edit the sources instead.\n' + parts.join('\n'));
console.log('wrote worker/dist/worker.js');
