// Generates twenty/index.html (served at /twenty/) from index.html: the same app playing the improved
// 20-move certificate (js/certificate20.js) instead of the paper's 21-move one.
// Usage: node tools/make-twenty.mjs        (rerun after editing index.html)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
let html = readFileSync(root + 'index.html', 'utf8');

const PAPER = 'https://github.com/openai/math/blob/main/preprints/Snaky-in-21-Maker-moves-September-25-2026/article.pdf';
const RESEARCH = 'https://github.com/KaiaSage/snaky-demo/tree/claude/research-snaky-20/research/snaky20';

// Each replacement must match exactly once, so edits to index.html can't silently skip one.
const swaps = [
  ['<title>Snaky in 21</title>', '<title>Snaky in 20</title>'],
  ['<meta property="og:title" content="Snaky in 21">', '<meta property="og:title" content="Snaky in 20">'],
  ['<meta property="og:url" content="https://kaiasage.github.io/snaky-demo/">', '<meta property="og:url" content="https://kaiasage.github.io/snaky-demo/twenty/">'],
  ['href="css/style.css"', 'href="../css/style.css"'],
  ['<script src="js/certificate.js"></script>', '<script src="../js/certificate20.js"></script>'],
  ['<script src="js/engine.js"></script>', '<script src="../js/engine.js"></script>'],
  ['<script src="js/app.js"></script>', '<script src="../js/app.js"></script>'],
  ['· 728 proof cards</p>', '· 758 proof cards · improved</p>'],
  ['<h1>Snaky in <span class="seal">21</span></h1>', '<h1>Snaky in <span class="seal">20</span></h1>'],
  [/<p class="lede">[\s\S]*?<\/p>/, `<p class="lede">The same game as <a href="../">Snaky in 21</a>, but Black plays an improved strategy: the paper's
        cards plus 30 new ones, found by computer search and checked with the paper's own verifier. Black now always
        wins within 20 moves, and after a diagonal or knight's-move first reply within 18. How long can you make it take?</p>`],
  ['keeps the 21 line</span>', 'keeps the 20 line</span>'],
  ['<span class="of"> / 21</span>', '<span class="of"> / 20</span>'],
  ['<span id="forced">21</span>', '<span id="forced">20</span>'],
  [/<p>The final card, 727,[\s\S]*?<\/p>/, `<p>The final card here is 757. Like the paper's 727 it needs nothing (A = ∅) and fits in a 17×17 square, but
        it has height 20. Its pivot is tengen, K10. Of its children, single-stone cards of height 17 (new cards 738 and
        749, in all their rotations) answer every diagonal and knight's-move reply, so those games end by move 18. Only a
        reply directly next to tengen keeps Black busy until move 20.</p>`],
  ['that is part of how 21 is reachable. A Black that also took every free win would never need more than 21\n        moves, and would often finish much sooner.',
    'the improved certificate adds cards that fit the extra stones Black happens to have, which is where the saved moves come from.'],
  [/<p>Card 727 is a hand of 32 placed cards in six groups \(Table 1 of the paper\)\.[^<]*<\/p>/,
    `<p>Card 757 is a hand of placed cards: the paper's height-15 cards plus the new height-17 ones. Step through them and
        watch their common envelope shrink until only the pivot is left. That is why Black needs nothing to start.</p>`],
  ['An improved strategy that always wins within 20 moves is at <a href="twenty/">Snaky in 20</a>.',
    'The paper\'s original 21-move strategy is at <a href="../">Snaky in 21</a>.'],
  ['Open any of the 728 cards.', 'Open any of the 758 cards (728 onward are new).'],
  [/(The 728-card certificate Black plays here is its Appendix D,[^<]*)/,
    `The certificate Black plays here starts with its Appendix D, byte for byte, followed by 30 new cards that
        bring the bound to 20. The new cards are a draft: computer-checked, not yet reviewed by anyone else
        (<a href="${RESEARCH}" target="_blank" rel="noopener">how they were found and checked</a>). `],
];
for (const [from, to] of swaps) {
  const n = typeof from === 'string' ? html.split(from).length - 1 : (html.match(new RegExp(from.source, 'g')) || []).length;
  if (n !== 1) throw new Error(`expected exactly one match for ${String(from).slice(0, 60)}, found ${n}`);
  html = html.replace(from, to);
}
if (!html.includes(PAPER)) throw new Error('paper link missing');
mkdirSync(root + 'twenty', { recursive: true });
html = html.replace(/^<!doctype html>\n/i, (d) => d + '<!-- Generated by tools/make-twenty.mjs from index.html; edit that and rerun. -->\n');
writeFileSync(root + 'twenty/index.html', html);
console.log('wrote twenty/index.html');
